
target:
  _target_: src.util.dynamic_load
  item: src.aux.report_mean_fusion.entry

# checkpoint: "/media/D3/tester/reresearch/_plt/propertest/finetune/test.ckpt"
checkpoint: 
  - "./checkpoint/finetune/mean_fusion/classifier.ckpt"
  - "./checkpoint/finetune/mean_fusion/classifier-v1.ckpt"
  - "./checkpoint/finetune/mean_fusion/classifier-v2.ckpt"
  - "./checkpoint/finetune/mean_fusion/classifier-v3.ckpt"
  - "./checkpoint/finetune/mean_fusion/classifier-v4.ckpt"

device: "cuda:5"
data_dir: "./data/faithful/test"

pl_cls_version: 2

schema:
  - _target_: dataloader.TUEVDataset.TUEVDataField
    _args_:
      - "signal"
      - _target_: src.util.dynamic_load
        item: torch.float
      - _target_: src.util.dynamic_load
        item: src.util.staged_mu_law
  - _target_: dataloader.TUEVDataset.TUEVDataField
    _args_:
      - "label"
      - _target_: src.util.dynamic_load
        item: torch.long
      - _target_: src.util.dynamic_load
        item: src.util.minus_one

batch_size: 32
num_workers: 4
n_class: 6

metrics:
  - balanced_accuracy
  - cohen_kappa
  - f1_weighted