rng_seeding:
  seed: 0
  workers: True

trainer:
  _target_: lightning.pytorch.Trainer
  fast_dev_run: False
  accelerator: 'gpu'
  strategy: 'auto'
  devices: [1]
  logger: 
    - _target_: lightning.pytorch.loggers.wandb.WandbLogger
      name: "backbone_model_mulaw"
      project: "proper_pretraining"
      save_dir: "./log/"
  default_root_dir: "./checkpoint"
  callbacks: 
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 1
      every_n_epochs: 10
      dirpath: "./checkpoint/pretrain/"
      filename: "mulaw"
  max_epochs: 100
  min_epochs: null
  check_val_every_n_epoch: 10
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: True
  enable_progress_bar: True
  enable_model_summary: True
  accumulate_grad_batches: 1
  gradient_clip_val: 1
  gradient_clip_algorithm: "norm"
  deterministic: True
  inference_mode: True
  use_distributed_sampler: True
  profiler: null
  detect_anomaly: False
  barebones: False

model:
  model_kwargs:
    in_channels: 1
    d_model: 128
    d_state: 128
    n_layer: 20
    n_ssm: null
    kernel_init: "diag-lin"
    kernel_mode: "diag"
    bidirectional: True
    d_cond: 512
    d_cond_embed: 128
    local_cond_ch: 0
    n_class: 22
    have_null_class: False
    self_gated: False

  ema_kwargs:
    beta: 0.999
    update_after_step: 100
    update_every: 10

  noise_sch_kwargs:
    num_train_timesteps: 50
    beta_start: 0.0001
    beta_end: 0.05
    beta_schedule: "squaredcos_cap_v2"
    prediction_type: "v_prediction"

  opt_kwargs:
    lr: 1e-4
    weight_decay: 0

  gen_kwargs:
    _target_: builtins.dict
    n_sample: 4
    shape: [1, 1000]
    save_intermediate: False
    root: "./gen/"
    save_dir: "backbone_model_mulaw"
    rescale: 1e-4
    ch_names: 
      _target_: src.util.dynamic_load
      item: src.preprocessing.bipolar_ch_order
    sfreq: 200
    inv_data_trans:
      _target_: src.util.dynamic_load
      item: src.util.inv_mu_law

data:
  _target_: builtins.dict
  root: "./data/single_ch"
  train_dir: "train"
  val_dir: "val"
  test_dir: "test"
  batch_size: 108 # 64 + 32 + 8 + 4
  num_workers: 4
  schema:
    - _target_: dataloader.TUEVDataset.TUEVDataField
      _args_:
        - "data"
        - _target_: src.util.dynamic_load
          item: torch.float
        - _target_: src.util.dynamic_load
          item: src.util.mu_law
    - _target_: dataloader.TUEVDataset.TUEVDataField
      _args_:
        - "ch_idx"
        - _target_: src.util.dynamic_load
          item: torch.long
  stft_kwargs: null
