
# checkpoint: "/media/D3/tester/reresearch/_plt/propertest/finetune/test.ckpt"
checkpoint: "./checkpoint/finetune/base/classifier.ckpt"
device: "cuda:0"
data_dir: "/media/D3/tester/v2.0.1/edf/labram_processed_eval_withrepeat_bipolar"

schema:
  - _target_: dataloader.TUEVDataset.TUEVDataField
    _args_:
      - "signal"
      - _target_: src.util.dynamic_load
        item: torch.float
      - _target_: src.util.dynamic_load
        item: src.util.div_100_staged_mu_law
  - _target_: dataloader.TUEVDataset.TUEVDataField
    _args_:
      - "label"
      - _target_: src.util.dynamic_load
        item: torch.long
      - _target_: src.util.dynamic_load
        item: src.util.minus_one

batch_size: 32
num_workers: 4
n_class: 6

metrics:
  - balanced_accuracy
  - cohen_kappa
  - f1_weighted